# Site settings
title:          Our Healthcare HK
description:    "Raising awareness for the healthcare system in Hong Kong"
baseurl:        ""
url:            "https://openmedicshk.github.io"

# Author
author:
  name:         Mister Mochi
  url:          https://github.com/mistermochi
  email:        mochitravels@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Permalinks
permalink:      /data/:title/

# Collections
collections:
  HAhospital:
    output: true
    permalink: /HAHospital/:title/

# Layouts
defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'HAhospital'
    values:
      layout: 'HAHosp'
