# Site settings
title:          OpenMedicsHK
description:    "Raising awareness for the healthcare crises in Hong Kong"
baseurl:        ""
url:            "https://openmedicshk.github.io"

# Author
author:
  name:         Mister Mochi
  url:          https://github.com/mistermochi
  email:        mochitravels@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Permalinks
permalink:      /:year-:month-:day/:title
