# Site settings
title:          Phantom-jekyll
description:    "Elegant minimalistic Jekyll theme ported from work of HTML5Up"
baseurl:        "/phantom-jekyll"
url:            "https://mistermochi.github.io"

# Author
author:
  name:         Mister Mochi
  url:          https://github.com/mistermochi
  email:        mochitravels@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Permalinks
permalink:      /:year-:month-:day/:title
